name: Pull Request Hook
on: pull_request
jobs:
  payload:
    runs-on: ubuntu-latest
    steps:
      - run: cat $GITHUB_EVENT_PATH
      - name: request api
        run: curl -H "Authorization: token {{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/SnowCait/github-hooks-sandbox/pulls/5/reviews
