name: Pull Request Hook
on: [pull_request, pull_request_review, pull_request_review_comment]
jobs:
  payload:
    runs-on: ubuntu-latest
    steps:
      - run: cat $GITHUB_EVENT_PATH
      - name: request api
        run: 'curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/SnowCait/github-hooks-sandbox/pulls/5/reviews'
      - name: Reviews
        id: reviews
        uses: octokit/request-action@v2.0.2
        with:
          route: GET /repos/{owner}/{repo}/pulls/{pull_number}/reviews
          owner: SnowCait
          repo: github-hooks-sandbox
          pull_number: ${{ github.event.pull_request.number }}
      - name: Response
        run: echo ${{ steps.reviews.outputs.data }}
      - name: GitHub Script
        uses: actions/github-script@v3.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const reviews = ${{ steps.reviews.outputs.data }}
            for (const review in reviews.reverse()) {
              console.log(`${review.user.login}: ${review.state}`
            }
